############################
## CHANGE THESE
############################

baseURL: "https://kaly-m.github.io/portfolio"
title: portfolio

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"] # keep them minimalist
languageCode: "fr"
enableRobotsTXT: true # authorize web crawler

# enable raw html
markup:
  goldmark:
    renderer:
      unsafe: true
