############################
## CHANGE THESE
############################

baseURL: "https://kaly-m.github.io/qubt"
title: portfolio

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "fr"
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
