############################
## CHANGE THESE
############################

baseURL: "https://kaly-m.github.io/qubt"
title: portefolio

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "fr"
enableRobotsTXT: true
