############################
## Navbar
############################

main:
- name: Accueil
  url: /
  weight: 10
- name: Projets
  url: /projets/
  weight: 20
- name: À propos
  url: /about/
  weight: 30
